FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements-parser.txt ./
RUN pip install --no-cache-dir -r requirements-parser.txt
RUN playwright install --with-deps chromium

COPY app ./app
COPY scripts ./scripts

CMD ["python", "-m", "scripts.run_parser"]